export const permisos = {
    ROLE_ADMIN: 'ROLE_ADMIN',
    ROLE_CUSTOMER_EXTERNAL: 'ROLE_CUSTOMER_EXTERNAL',
    ROLE_CUSTOMER_INTERNAL: 'ROLE_CUSTOMER_INTERNAL',
    ROLE_CONSULTANT: 'ROLE_CONSULTANT',
    ROLE_CARRIER: 'ROLE_CARRIER',
    ROLE_PRODUCER: 'ROLE_PRODUCER',

}